name: ARM Template Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
    branches: [ main ]

jobs:
  armttk:
    name: ARM TTK Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: microsoft/action-armttk@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          glob_pattern: "src/**/*.json"